<script>
  /** @type {import('./$types').PageData} */
  export let data;
</script>

<svelte:head>
  <title>
    Surviving Ourselves: A Work of Human-Directed AI Generated Fiction of Two
    Brothers Fighting for Survival on the Run in 2000s Austin | {data.subtitle}
  </title>
  <!-- {@html data.headScript} -->
</svelte:head>

<div class="callout">
  <div class="content">
    <small>Posted on: {data.date}</small>
    <h1>{data.title}</h1>
    <h2>{data.subtitle}</h2>
    <div class="the-content">{@html data.content}</div>
    {#if data.nextLink !== null}
      <a class="button red" href="/blog/{data.nextLink}">Next</a>
    {:else}
      <p>To Be Continued...</p>
      <a class="button grey" href="/likes-blog">Like Our Story?</a>
    {/if}
  </div>
  <div class="imageGroup">
    <img src={data.image} alt={data.title + " cover art"} />
    <span class="caption">
      <small>Generated by DALL-E</small>
    </span>
  </div>
</div>

<style>
  .button {
    display: inline-block;
    padding: 0.5rem 1rem;
    color: rgb(255, 255, 255);
    text-decoration: none;
    border-radius: 0.25rem;
    font-weight: bold;
    transition: all 0.2s ease-in-out;
  }
  .button.red {
    background-color: #db2525;
  }
  .button.grey {
    background-color: #333;
  }
  .callout {
    display: flex;
    flex-direction: row;
    gap: 40px;
  }
  img {
    max-width: 100%;
  }
  .imageGroup {
    display: flex;
    flex-direction: column;
    gap: 10px;
    width: 50%;
  }
  .content {
    width: 50%;
    padding: 40px;
  }
  p,
  .the-content {
    font-size: 1.3rem;
  }

  @media (max-width: 768px) {
    .callout {
      flex-direction: column;
    }
    .imageGroup {
      width: 100%;
    }
    .content {
      width: 100%;
      padding: 20px;
    }
  }
</style>
