<script>
  /** @type {import('./$types').PageData} */
  export let data;
</script>

<svelte:head>
  <title>
    Surviving Ourselves: A Work of Human-Directed AI Generated Fiction of Two
    Brothers Fighting for Survival on the Run in 2000s Austin | {data.subtitle}
  </title>
</svelte:head>

<div class="callout">
  <div class="content">
    <small>Posted on: {data.date}</small>
    <h1>{data.title}</h1>
    <h2>{data.subtitle}</h2>
    <div class="the-content">{@html data.content}</div>
    <p>Stay Continued...</p>
  </div>
  <div class="imageGroup">
    <img src={data.image} alt={data.title + " cover art"} />
    <span class="caption">
      <small>Generated by DALL-E</small>
    </span>
  </div>
</div>

<style>
  .callout {
    display: flex;
    flex-direction: row;
    gap: 40px;
  }
  img {
    max-width: 100%;
  }
  .imageGroup {
    display: flex;
    flex-direction: column;
    gap: 10px;
    width: 50%;
  }
  .content {
    width: 50%;
    padding: 40px;
  }
  p,
  .the-content {
    font-size: 1.3rem;
  }

  @media (max-width: 768px) {
    .callout {
      flex-direction: column;
    }
    .imageGroup {
      width: 100%;
    }
    .content {
      width: 100%;
      padding: 20px;
    }
  }
</style>
