import { error } from '@sveltejs/kit';

/** @type {import('./$types').PageLoad} */
export function load({ params }) {
  if (params.slug === 'chapter-1-the-night-it-all-began') {
    return {
      headScript: '<script type="application/ld+json">{"@context": "http://schema.org","@type": "Article","name": "Surviving Ourselves: A Work of Human-Directed AI Generated Fiction of Two Brothers Fighting for Survival on the Run in 2000s Austin","image": "https://www.surviving-ourselves.com/chapter_1.png","articleBody": "Chapter 1: The Night It All Began</H2> <DIV class=\"the-content svelte-1q6jwfr\"><P>It was 2 am, and Alex and Jake trudged down the dimly lit streets of the south side of Austin. The constant growling of their stomachs is a reminder of their dire situation. They were not only on the run from the law due to violating their parole but they were also homeless. They had been kicked out of the government housing where their mother lived, as she was not supposed to have them there while on parole. Now, they were living on the streets, sleeping in abandoned buildings and dope houses with no place to call home.</P><P>As they walked down Ben White, the smell of burgers and fries wafting out of a Jack-n-the-box&#39;s drive-thru window, caught their attention. They knew they couldn&#39;t afford a meal, but the smell was too tempting to resist. Jake walked up to the drive-thru, trying to look as presentable as possible, and knocked on the window while Alex sat on the curb, taking off his shoes. His feet were swollen and covered in sores, a result of the poor hygiene and living conditions of being on the street. Alex thought to himself, “I&#39;ve been through worse. I&#39;ve been in the juvenile detention center, I&#39;ve seen the worst of people, I&#39;ve been beaten, and I&#39;ve been hungry, this ain&#39;t shit.”</P><P>More of a pep talk than the truth.</P><P>As Jake walked back with the food, his pager beeped. He handed Alex the food and walked towards the nearby payphone, leaving Alex alone with his thoughts. Alex took a bite of the burger, savoring the taste, but also aware that this could be the last decent meal they would have for a while.</P><P>As Jake returned from the payphone, his expression was serious. “That was our half-brother,” he said. “He&#39;s gotta lick, but we need to find a car.” Alex felt a spark of hope. They were desperate, and it seemed like this could be their only chance, but at what cost? They&#39;ve been through juvenile prison, they’re homeless, and they&#39;re hardened and ready for whatever comes next, even if it means breaking the law again."}</script>',
      image: '/chapter_1.png',
      title: 'Surviving Ourselves: A Work of Human-Directed AI Generated Fiction of Two Brothers Fighting for Survival on the Run in 2000s Austin',
      subtitle: "Chapter 1: The Night It All Began",
      content: "<p>It was 2 am, and Alex and Jake trudged down the dimly lit streets of the south side of Austin. The constant growling of their stomachs is a reminder of their dire situation. They were not only on the run from the law due to violating their parole but they were also homeless. They had been kicked out of the government housing where their mother lived, as she was not supposed to have them there while on parole. Now, they were living on the streets, sleeping in abandoned buildings and dope houses with no place to call home.</p><p>As they walked down Ben White, the smell of burgers and fries wafting out of a Jack-n-the-box's drive-thru window, caught their attention. They knew they couldn't afford a meal, but the smell was too tempting to resist. Jake walked up to the drive-thru, trying to look as presentable as possible, and knocked on the window while Alex sat on the curb, taking off his shoes. His feet were swollen and covered in sores, a result of the poor hygiene and living conditions of being on the street. Alex thought to himself, &ldquo;I've been through worse. I've been in the juvenile detention center, I've seen the worst of people, I've been beaten, and I've been hungry, this ain't shit.&rdquo;</p><p>More of a pep talk than the truth.</p><p>As Jake walked back with the food, his pager beeped. He handed Alex the food and walked towards the nearby payphone, leaving Alex alone with his thoughts. Alex took a bite of the burger, savoring the taste, but also aware that this could be the last decent meal they would have for a while.</p><p>As Jake returned from the payphone, his expression was serious. &ldquo;That was our half-brother,&rdquo; he said. &ldquo;He's gotta lick, but we need to find a car.&rdquo; Alex felt a spark of hope. They were desperate, and it seemed like this could be their only chance, but at what cost? They've been through juvenile prison, they&rsquo;re homeless, and they're hardened and ready for whatever comes next, even if it means breaking the law again.</p>",
      date: "01/14/2023"
    };
  }

  throw error(404, 'Not found');
}
