import { error } from '@sveltejs/kit';

/** @type {import('./$types').PageLoad} */
export function load({ params }) {
  if (params.slug === 'chapter-1-the-night-it-all-began') {
    return {
      headScript: '<script type="application/ld+json">{"@context": "http://schema.org","@type": "Article","name": "Surviving Ourselves: A Work of Human-Directed AI Generated Fiction of Two Brothers Fighting for Survival on the Run in 2000s Austin","image": "https://www.surviving-ourselves.com/chapter_1.png","articleBody": "Chapter 1: The Night It All Began</H2> <DIV class=\"the-content svelte-1q6jwfr\"><P>It was 2 am, and Alex and Jake trudged down the dimly lit streets of the south side of Austin. The constant growling of their stomachs is a reminder of their dire situation. They were not only on the run from the law due to violating their parole but they were also homeless. They had been kicked out of the government housing where their mother lived, as she was not supposed to have them there while on parole. Now, they were living on the streets, sleeping in abandoned buildings and dope houses with no place to call home.</P><P>As they walked down Ben White, the smell of burgers and fries wafting out of a Jack-n-the-box&#39;s drive-thru window, caught their attention. They knew they couldn&#39;t afford a meal, but the smell was too tempting to resist. Jake walked up to the drive-thru, trying to look as presentable as possible, and knocked on the window while Alex sat on the curb, taking off his shoes. His feet were swollen and covered in sores, a result of the poor hygiene and living conditions of being on the street. Alex thought to himself, “I&#39;ve been through worse. I&#39;ve been in the juvenile detention center, I&#39;ve seen the worst of people, I&#39;ve been beaten, and I&#39;ve been hungry, this ain&#39;t shit.”</P><P>More of a pep talk than the truth.</P><P>As Jake walked back with the food, his pager beeped. He handed Alex the food and walked towards the nearby payphone, leaving Alex alone with his thoughts. Alex took a bite of the burger, savoring the taste, but also aware that this could be the last decent meal they would have for a while.</P><P>As Jake returned from the payphone, his expression was serious. “That was our half-brother,” he said. “He&#39;s gotta lick, but we need to find a car.” Alex felt a spark of hope. They were desperate, and it seemed like this could be their only chance, but at what cost? They&#39;ve been through juvenile prison, they’re homeless, and they&#39;re hardened and ready for whatever comes next, even if it means breaking the law again."}</script>',
      image: '/chapter_1.png',
      title: 'Surviving Ourselves: A Work of Human-Directed AI Generated Fiction of Two Brothers Fighting for Survival on the Run in 2000s Austin',
      subtitle: "Chapter 1: The Night It All Began",
      content: "<p>It was 2 am, and Alex and Jake trudged down the dimly lit streets of the south side of Austin. The constant growling of their stomachs is a reminder of their dire situation. They were not only on the run from the law due to violating their parole but they were also homeless. They had been kicked out of the government housing where their mother lived, as she was not supposed to have them there while on parole. Now, they were living on the streets, sleeping in abandoned buildings and dope houses with no place to call home.</p><p>As they walked down Ben White, the smell of burgers and fries wafting out of a Jack-n-the-box's drive-thru window, caught their attention. They knew they couldn't afford a meal, but the smell was too tempting to resist. Jake walked up to the drive-thru, trying to look as presentable as possible, and knocked on the window while Alex sat on the curb, taking off his shoes. His feet were swollen and covered in sores, a result of the poor hygiene and living conditions of being on the street. Alex thought to himself, &ldquo;I've been through worse. I've been in the juvenile detention center, I've seen the worst of people, I've been beaten, and I've been hungry, this ain't shit.&rdquo;</p><p>More of a pep talk than the truth.</p><p>As Jake walked back with the food, his pager beeped. He handed Alex the food and walked towards the nearby payphone, leaving Alex alone with his thoughts. Alex took a bite of the burger, savoring the taste, but also aware that this could be the last decent meal they would have for a while.</p><p>As Jake returned from the payphone, his expression was serious. &ldquo;That was our half-brother,&rdquo; he said. &ldquo;He's gotta lick, but we need to find a car.&rdquo; Alex felt a spark of hope. They were desperate, and it seemed like this could be their only chance, but at what cost? They've been through juvenile prison, they&rsquo;re homeless, and they're hardened and ready for whatever comes next, even if it means breaking the law again.</p>",
      date: "01/14/2023",
      slug: 'chapter-1-the-night-it-all-began',
      nextLink: 'chapter-2-the-hunt-for-the-caddy'
    };
  }

  if (params.slug === 'chapter-2-the-hunt-for-the-caddy') {
    return {
      headScript: '<script type="application/ld+json">{"@context": "http://schema.org","@type": "Article","name": "Surviving Ourselves: A Work of Human-Directed AI Generated Fiction of Two Brothers Fighting for Survival on the Run in 2000s Austin","image": "https://www.surviving-ourselves.com/chapter_1.png","articleBody": "Chapter 1: The Night It All Began</H2> <DIV class=\"the-content svelte-1q6jwfr\"><P>It was 2 am, and Alex and Jake trudged down the dimly lit streets of the south side of Austin. The constant growling of their stomachs is a reminder of their dire situation. They were not only on the run from the law due to violating their parole but they were also homeless. They had been kicked out of the government housing where their mother lived, as she was not supposed to have them there while on parole. Now, they were living on the streets, sleeping in abandoned buildings and dope houses with no place to call home.</P><P>As they walked down Ben White, the smell of burgers and fries wafting out of a Jack-n-the-box&#39;s drive-thru window, caught their attention. They knew they couldn&#39;t afford a meal, but the smell was too tempting to resist. Jake walked up to the drive-thru, trying to look as presentable as possible, and knocked on the window while Alex sat on the curb, taking off his shoes. His feet were swollen and covered in sores, a result of the poor hygiene and living conditions of being on the street. Alex thought to himself, “I&#39;ve been through worse. I&#39;ve been in the juvenile detention center, I&#39;ve seen the worst of people, I&#39;ve been beaten, and I&#39;ve been hungry, this ain&#39;t shit.”</P><P>More of a pep talk than the truth.</P><P>As Jake walked back with the food, his pager beeped. He handed Alex the food and walked towards the nearby payphone, leaving Alex alone with his thoughts. Alex took a bite of the burger, savoring the taste, but also aware that this could be the last decent meal they would have for a while.</P><P>As Jake returned from the payphone, his expression was serious. “That was our half-brother,” he said. “He&#39;s gotta lick, but we need to find a car.” Alex felt a spark of hope. They were desperate, and it seemed like this could be their only chance, but at what cost? They&#39;ve been through juvenile prison, they’re homeless, and they&#39;re hardened and ready for whatever comes next, even if it means breaking the law again."}</script>',
      image: '/chapter_2.png',
      title: 'Surviving Ourselves: A Work of Human-Directed AI Generated Fiction of Two Brothers Fighting for Survival on the Run in 2000s Austin',
      subtitle: "Chapter 2: The Hunt for the Caddy",
      content: "<p>Alex and Jake were on a mission to find a 92 Fleetwood Caddy. Their half-brother, Q, had told them that the car was wanted because it had matching doors that he needed for his own car. Alex and Jake knew of a place where they could find the car, an apartment complex in Riverside, from past experiences.</p>As they arrived at the complex, they quickly scanned the parking lot for the Caddy. It was there, just as they had hoped. The car had already been stolen once before, and the steering column had been broken, but they knew they just needed to stick an item in the column to pull the teeth and start the car. They quickly found a wire hanger, bent and shaped it to fit the ignition, and the car roared to life.<p>With the car in their possession, they headed towards the East side of town, where Q was waiting for them in the SHACK. As they drove through the neighborhood, they couldn't help but feel a sense of unease. The area was known for being dangerous and they knew that they were in the middle of a crack-dealing operation. But they were focused on their goal and were determined to deliver the car to Q, who they looked up to due to his success.</p><p>When they finally arrived at the designated spot, Q was waiting for them. He was pleased to see the car and gave them the ounce of crack as promised. However, the brothers now had no car and needed a ride from Q to get back to the southside. They knew that they had taken a risk, but they were also aware of the potential payoff. They were ready for whatever came next, whether it was success or failure.</p>",
      date: "01/16/2023",
      slug: 'chapter-2-the-hunt-for-the-caddy',
      nextLink: 'chapter-3-a-turn-of-events'
    };
  }

  if (params.slug === 'chapter-3-a-turn-of-events') {
    return {
      headScript: '<script type="application/ld+json">{"@context": "http://schema.org","@type": "Article","name": "Surviving Ourselves: A Work of Human-Directed AI Generated Fiction of Two Brothers Fighting for Survival on the Run in 2000s Austin","image": "https://www.surviving-ourselves.com/chapter_1.png","articleBody": "Chapter 1: The Night It All Began</H2> <DIV class=\"the-content svelte-1q6jwfr\"><P>It was 2 am, and Alex and Jake trudged down the dimly lit streets of the south side of Austin. The constant growling of their stomachs is a reminder of their dire situation. They were not only on the run from the law due to violating their parole but they were also homeless. They had been kicked out of the government housing where their mother lived, as she was not supposed to have them there while on parole. Now, they were living on the streets, sleeping in abandoned buildings and dope houses with no place to call home.</P><P>As they walked down Ben White, the smell of burgers and fries wafting out of a Jack-n-the-box&#39;s drive-thru window, caught their attention. They knew they couldn&#39;t afford a meal, but the smell was too tempting to resist. Jake walked up to the drive-thru, trying to look as presentable as possible, and knocked on the window while Alex sat on the curb, taking off his shoes. His feet were swollen and covered in sores, a result of the poor hygiene and living conditions of being on the street. Alex thought to himself, “I&#39;ve been through worse. I&#39;ve been in the juvenile detention center, I&#39;ve seen the worst of people, I&#39;ve been beaten, and I&#39;ve been hungry, this ain&#39;t shit.”</P><P>More of a pep talk than the truth.</P><P>As Jake walked back with the food, his pager beeped. He handed Alex the food and walked towards the nearby payphone, leaving Alex alone with his thoughts. Alex took a bite of the burger, savoring the taste, but also aware that this could be the last decent meal they would have for a while.</P><P>As Jake returned from the payphone, his expression was serious. “That was our half-brother,” he said. “He&#39;s gotta lick, but we need to find a car.” Alex felt a spark of hope. They were desperate, and it seemed like this could be their only chance, but at what cost? They&#39;ve been through juvenile prison, they’re homeless, and they&#39;re hardened and ready for whatever comes next, even if it means breaking the law again."}</script>',
      image: '/chapter_3.png',
      title: 'Surviving Ourselves: A Work of Human-Directed AI Generated Fiction of Two Brothers Fighting for Survival on the Run in 2000s Austin',
      subtitle: "Chapter 3: A Turn of Events",
      content: "<p>As Q dropped Alex and Jake off on the southside, they found themselves back in front of the Jack-n-the-Box where they had gotten the burgers earlier. They knew that a dopefiend lived nearby and they had stayed with him before in exchange for crack. They were planning on going there again, but as they walked, they ran into a middle-aged white guy. At first, he whispered something that sounded like &ldquo;you got it?&rdquo;, and as they got closer, they realized that he was looking for crack.</p><p>With the ounce of crack that Q had given them, the brothers saw an opportunity. They sold him a small amount and in return, the man let them know about his friend who had a suite at the Red Roof Inn. He invited them to come with him and since they were only across the highway, they decided to take him up on his offer. As they walked towards the hotel, they couldn't help but feel a sense of curiosity.</p><p>As they entered the hotel, they were greeted by a luxurious suite that was beyond their wildest dreams. They were used to living on the streets and having no permanent place to call home. But now, they had the opportunity to observe and take in their temporary surroundings in a way they never have before. They couldn't help but feel a sense of awe as they looked around the room, taking note of the elegant furnishings, high-end decor, and overall opulence of the space. They knew that this was not a place they could stay for long, but for now, they were content to soak in the luxury and enjoy the moment.</p>",
      date: "01/16/2023",
      slug: 'chapter-3-a-turn-of-events',
      nextLink: null
    };
  }

  throw error(404, 'Not found');
}
